### ISSUE TITLE
Build on Ubunut 18.04 fails

### ISSUE THREAD

**Issue by davidlunarg** [JulAlx/TP-Link-UE300-UE330-Linux-Driver#1]
$ sudo make
make -C /lib/modules/5.4.0-58-generic/build SUBDIRS=/src/TP-Link-UE300-UE330-Linux-Driver/r8152-2.08.0 modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-58-generic'
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
arch/x86/Makefile:232: recipe for target 'archscripts' failed
make[1]: *** [archscripts] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-58-generic'
Makefile:17: recipe for target 'modules' failed
make: *** [modules] Error 2

$ uname -a
Linux jogger 5.4.0-58-generic #64~18.04.1-Ubuntu SMP Wed Dec 9 17:11:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JulAlx** [comment]
Won't work with Kernel branch 5. It only works with Kernel 4.xx.
